name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11.8
  FLUTTER_VERSION: 3.22.2

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory contents
      run: ls -la

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.22.0
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev clang cmake
        flutter doctor --verbose

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build Linux App
      run: |
        flutter config --no-analytics
        flet build linux --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }} --module-name main.py
      working-directory: ./
      timeout-minutes: 30

    - name: List build output
      run: find build/ -type f || echo "No files found in build directory"

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/linux/**/*.{AppImage,appimage}  # توسيع نطاق البحث ليشمل صيغ متعددة
        if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory contents
      run: ls -la

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.22.0
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build macOS App
      run: |
        flutter config --no-analytics
        flet build macos --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }} --module-name main.py
      working-directory: ./
      timeout-minutes: 30

    - name: List build output
      run: find build/ -type f || echo "No files found in build directory"

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/macos/**/*.app
        if-no-files-found: warn

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory contents
      shell: cmd
      run: dir

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.22.0
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Install Windows Build Tools
      run: |
        choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
      shell: cmd
      continue-on-error: true  # قد لا تكون ضرورية دائمًا، لكنها تضمن الاستمرار إذا كانت مثبتة بالفعل

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build Windows App
      shell: cmd
      run: |
        flutter config --no-analytics
        flet build windows --verbose --build-number=%BUILD_NUMBER% --build-version=%BUILD_VERSION% --module-name main.py
      working-directory: ./
      timeout-minutes: 30

    - name: List build output
      shell: cmd
      run: dir build /s /p || echo "No files found in build directory"

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/windows/**/*.{exe,EXE}  # توسيع نطاق البحث ليشمل صيغ متعددة
        if-no-files-found: warn

  build-aab:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory contents
      run: ls -la

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.22.0
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build AAB
      run: |
        flutter config --no-analytics
        flet build aab --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }} --module-name main.py
      working-directory: ./
      timeout-minutes: 30

    - name: List build output
      run: find build/ -type f || echo "No files found in build directory"

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: build/**/*.{aab,AAB}
        if-no-files-found: warn

  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory contents
      run: ls -la

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.22.0
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build APK
      run: |
        flutter config --no-analytics
        flet build apk --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }} --module-name main.py
      working-directory: ./
      timeout-minutes: 30

    - name: List build output
      run: find build/ -type f || echo "No files found in build directory"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/**/*.{apk,APK}
        if-no-files-found: warn

  build-ipa:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory contents
      run: ls -la

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.22.0
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build IPA
      run: |
        flutter config --no-analytics
        flet build ipa --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }} --module-name main.py
      working-directory: ./
      timeout-minutes: 30

    - name: List build output
      run: find build/ -type f || echo "No files found in build directory"

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: build/ios/**/*.{ipa,IPA}  # تحديد مسار أكثر دقة لـ IPA
        if-no-files-found: warn
