name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11.8
  FLUTTER_VERSION: 3.22.2

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev clang cmake
        flutter doctor --verbose

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build Linux App
      run: |
        flutter config --no-analytics
        flet build linux --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}
        ls -la build/linux/x64/release/bundle/
      working-directory: ./

    - name: Package AppImage
      run: |
        mkdir -p dist
        flutter build linux
        # Adjust path according to your project structure
        cp -r build/linux/x64/release/bundle/* dist/
      working-directory: ./

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: dist/*.AppImage
        if-no-files-found: error # Change to error to fail the job if no files found

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build Windows App
      shell: cmd
      run: |
        flutter config --no-analytics
        flet build windows --verbose --build-number=%BUILD_NUMBER% --build-version=%BUILD_VERSION%
        dir build\windows\runner\Release\
      working-directory: ./

    - name: Package Windows App
      shell: cmd
      run: |
        mkdir dist
        copy build\windows\runner\Release\*.exe dist\
      working-directory: ./

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/*.exe
        if-no-files-found: error

  build-ipa:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Get Flutter Dependencies
      run: flutter pub get
      working-directory: ./

    - name: Build IPA
      run: |
        flutter config --no-analytics
        flet build ipa --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}
        ls -la build/ios/ipa/
      working-directory: ./

    - name: Package IPA
      run: |
        mkdir -p dist
        cp build/ios/ipa/*.ipa dist/
      working-directory: ./

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: dist/*.ipa
        if-no-files-found: error
