name: All Builds (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11.8
  FLUTTER_VERSION: 3.22.2

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet  # تثبيت flet CLI
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        else
          echo "No requirements.txt found, skipping additional dependency installation"
        fi
      continue-on-error: true

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev clang cmake
        flutter doctor --verbose

    - name: Build Linux App
      run: |
        flutter config --no-analytics
        flet build linux --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}
      timeout-minutes: 30

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/linux/**/*.AppImage
        if-no-files-found: warn

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet  # تثبيت flet CLI
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi
      continue-on-error: true

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Build macOS App
      run: |
        flutter config --no-analytics
        flet build macos --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}
      timeout-minutes: 30

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/macos/**/*.app
        if-no-files-found: warn

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet  # تثبيت flet CLI
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi
      continue-on-error: true

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Build Windows App
      shell: cmd
      run: |
        flutter config --no-analytics
        flet build windows --verbose --build-number=%BUILD_NUMBER% --build-version=%BUILD_VERSION%
      timeout-minutes: 30

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/windows/**/*.exe
        if-no-files-found: warn

  build-aab:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet  # تثبيت flet CLI
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi
      continue-on-error: true

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Build AAB
      run: |
        flutter config --no-analytics
        flet build aab --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}
      timeout-minutes: 30

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-aab
        path: build/**/*.aab
        if-no-files-found: warn

  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet  # تثبيت flet CLI
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi
      continue-on-error: true

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Build APK
      run: |
        flutter config --no-analytics
        flet build apk --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}
      timeout-minutes: 30

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/**/*.apk
        if-no-files-found: warn

  build-ipa:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet  # تثبيت flet CLI
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt || echo "Failed to install dependencies, continuing anyway"
        fi
      continue-on-error: true

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Build IPA
      run: |
        flutter config --no-analytics
        flet build ipa --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}
      timeout-minutes: 30

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: build/**/*.ipa
        if-no-files-found: warn
